
# curl --location --request GET 'localhost:3001/mat'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "paginaActual": 1,
#    "cantidadAVer": 2
#}'
GET localhost:3001/mat
Content-Type: application/json

{
  "paginaActual": 1,
  "cantidadAVer": 2
}

###

POST localhost:3001/car
Content-Type: application/json

{
"nombre": "Programacion Orientada a Objetos II"
}

###

GET localhost:3001/car
Content-Type: application/json

{
}

###

GET localhost:3001/mat
Content-Type: application/json

{
}

###

DELETE localhost:3001/car/5
Content-Type: application/json
###

