
# curl --location --request GET 'localhost:3001/mat'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "paginaActual": 1,
#    "cantidadAVer": 2
#}'
GET localhost:3001/mat
Content-Type: application/json

{
  "paginaActual": 1,
  "cantidadAVer": 2
}

###

POST localhost:3001/car
Content-Type: application/json

{
"nombre": "Programacion Orientada a Objetos II"
}

###

POST localhost:3001/mat
Content-Type: application/json
Authorization: Basic cGVyc2lzdGVuY2lhOjEyMzQ=

{
  "nombre": "Programacion Orientada a Objetos III",
  "carreraId": ["4", "3"]
}

###

GET localhost:3001/car
Content-Type: application/json

{
}

###

GET localhost:3001/mat
Content-Type: application/json

{
}

###

DELETE localhost:3001/car/5
Content-Type: application/json
###

Basic cGVyc2lzdGVuY2lhOjEyMzQ=

token: cGVyc2lzdGVuY2lhOjEyMzQ=


###

# curl --location --request GET 'localhost:3001/mat'
#--header 'Authorization: Basic cGVyc2lzdGVuY2lhOjEyMzQ='
#--header 'Content-Type: application/json'
#--data-raw '{
#    "paginaActual": 1,
#    "cantidadAVer": 2
#}'
GET localhost:3001/mat
Authorization: Basic cGVyc2lzdGVuY2lhOjEyMzQ=
Content-Type: application/json

{
  "paginaActual": 1,
  "cantidadAVer": 2
}

###

# curl --location --request GET 'localhost:3001/mat'
#--header 'Authorization: Basic cGVyc2lzdGVuY2lhOjEyMzQ='
#--header 'Content-Type: application/json'
#--data-raw '{
#    "paginaActual": 1,
#    "cantidadAVer": 2
#}'
GET localhost:3001/car
Authorization: Basic cGVyc2lzdGVuY2lhOjEyMzQ=
Content-Type: application/json

{
  "paginaActual": 1,
  "cantidadAVer": 2
}

###

POST localhost:3001/user
Authorization: Basic cGVyc2lzdGVuY2lhMjo0MzIx
Content-Type: application/json

###



